# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('ssid', models.CharField(max_length=200)),
                ('portal_url', models.CharField(max_length=1000)),
                ('aaa_ip', models.CharField(max_length=200)),
                ('aaa_secret', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ap',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer'),
        ),
    ]
