# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_customer_wlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
