# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gr_customer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='gr_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='gr_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='pi_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='pi_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
