# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20160510_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aaa_port',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
